### PR TITLE
update your source homie

### PR DESCRIPTION
**Pull request by LEVIXDDLMAO**

### CODE REVIEW

**Comment by LEVIXDDLMAO** [comment]
homie i found out why stages aren't working

**Comment by LEVIXDDLMAO** [comment]
on the indie cross port

**Comment by MemeHoovy** [comment]
hm?

**Comment by LEVIXDDLMAO** [comment]
i got cuphead stages to work!! im fixing the code right now

**Comment by MemeHoovy** [comment]
oh sweet

**Comment by LEVIXDDLMAO** [comment]
yeah! just possing-

**Comment by LEVIXDDLMAO** [comment]
well the player placements

**Comment by LEVIXDDLMAO** [comment]
ill update you when i fix it

**Comment by LEVIXDDLMAO** [comment]
almost there

**Comment by LEVIXDDLMAO** [comment]
i found out why its because the weekcup on the weeks thing didnt work as assets, so i had to add a cup folder and then put the images

**Comment by MemeHoovy** [comment]
...so it was looking for a subfolder 😐

**Comment by LEVIXDDLMAO** [comment]
yeah-

**Comment by LEVIXDDLMAO** [comment]
image
boi what the hell boi

**Comment by MemeHoovy** [comment]
well the offsets are fucked, and the stage's are too small, but atleast they work now

**Comment by LEVIXDDLMAO** [comment]
yeah

**Comment by LEVIXDDLMAO** [comment]
heyyy

**Comment by MemeHoovy** [comment]
what?

**Comment by LEVIXDDLMAO** [comment]
do you want me to push the changes ? so and we can try to find this out?

**Comment by MemeHoovy** [comment]
sure, I've gotta try and fix my sleep schedule, I woke up like shit today when I was up all night working

**Comment by LEVIXDDLMAO** [comment]
sad,

**Comment by MemeHoovy** [comment]
very

**Comment by LEVIXDDLMAO** [comment]
there  i pushed the changes

**Comment by LEVIXDDLMAO** [comment]
did you test port it?

**Comment by MemeHoovy** [comment]
not yet

**Comment by LEVIXDDLMAO** [comment]
im testing it rn dont worry

**Comment by LEVIXDDLMAO** [comment]
no errors but stage is still broken

**Comment by MemeHoovy** [comment]
a

**Comment by LEVIXDDLMAO** [comment]
sad-

**Comment by LEVIXDDLMAO** [comment]
i got this now

**Comment by LEVIXDDLMAO** [comment]
image

**Comment by LEVIXDDLMAO** [comment]
i needed to change the zoom

**Comment by MemeHoovy** [comment]
yeah, and fix the stages being too small

**Comment by LEVIXDDLMAO** [comment]
the stage is fine just the zoom was 0.8 when it needed to be 0.6

**Comment by MemeHoovy** [comment]
k I made the stages bigger

**Comment by LEVIXDDLMAO** [comment]
oh

**Comment by LEVIXDDLMAO** [comment]
has it worked?

**Comment by MemeHoovy** [comment]
idk yet

**Comment by LEVIXDDLMAO** [comment]
:[

**Comment by MemeHoovy** [comment]
:]

**Comment by MemeHoovy** [comment]
dw, we'll figure it out, I'm sure

**Comment by LEVIXDDLMAO** [comment]
okay

**Comment by LEVIXDDLMAO** [comment]
image
HOMIE

**Comment by LEVIXDDLMAO** [comment]
YOOOOOo

**Comment by LEVIXDDLMAO** [comment]
ILL COMMIT CHANGES SOON JUST WAIT

**Comment by LEVIXDDLMAO** [comment]
DONT DO ANYTHING

**Comment by MemeHoovy** [comment]
ok 👍🏻

**Comment by LEVIXDDLMAO** [comment]
im using a lua port and then converting it to haxe

**Comment by MemeHoovy** [comment]
neato

**Comment by LEVIXDDLMAO** [comment]
image
 FIXED IT LETS GOO

**Comment by MemeHoovy** [comment]
👏🏻 👏🏻 👏🏻

**Comment by LEVIXDDLMAO** [comment]
YEAHHHHHH BUT NOW THE PLACEMENT FOR CUP AND BF AND THEN WE CAN WORK ON THE RAIN STAGE AND THEN WE CAN TAKE A BREAKKK

**Comment by MemeHoovy** [comment]
👌🏻

**Comment by LEVIXDDLMAO** [comment]
YEAHHH

**Comment by LEVIXDDLMAO** [comment]
I think the place ment is fine for now

**Comment by MemeHoovy** [comment]
it looks fine from what I saw

**Comment by LEVIXDDLMAO** [comment]
its just bf is a bit higher then cup

**Comment by MemeHoovy** [comment]
oh yeah, we just gotta move him down a tad bit

**Comment by MemeHoovy** [comment]
or move cuphead higher a bit, whichever works

**Comment by LEVIXDDLMAO** [comment]
lets move bf down since cuphead is good

**Comment by MemeHoovy** [comment]
alrighty then

**Comment by LEVIXDDLMAO** [comment]
^^

**Comment by LEVIXDDLMAO** [comment]
im fixing an push error rn dont do anything

**Comment by MemeHoovy** [comment]
k

**Comment by LEVIXDDLMAO** [comment]
thx

**Comment by MemeHoovy** [comment]
your welcome

**Comment by LEVIXDDLMAO** [comment]
almost got it

**Comment by LEVIXDDLMAO** [comment]
there

**Pull request merged**
